# Generated by Django 6.1.1 on 2026-10-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_orderitem_deal_orderitem_menu_item_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
