# Generated by Django 6.1.1 on 2026-10-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_accepted_by_order_cancel_reason_and_more'),
        ('pos', '0003_order_cancel_reason_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='online_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_order', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('counter', 'Counter'), ('online', 'Online')], default='counter', max_length=10),
        ),
    ]
